# Module 2: Essential Python Libraries

In this module, we will learn about some of the essential `Python` libraries for data science, such as *`numPy`, `pandas`,`matplotlib`, and `pyjanitor`*.

- **NumPy**
  `Numpy`, which stands for *Numerical Python*, is "the fundamental package for scientific computing in Python." In this module, we will briefly discuss `NumPy`. For example, we will demonstrate how to:
    - Create NumPy arrays and perform basic operations.
    - Apply mathematical functions to arrays.
  
- **Pandas**
  `pandas` is the main library for data cleaning and transformation (wrangling) in `Python`. We will use `pandas 2` in this course. Essential functions of the `pandas` library include:
    - Loading datasets.
    - Exploring and manipulating data.

- **Matplotlib**
    > Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. Matplotlib makes easy things easy and hard things possible.
    > - Create publication quality plots.
    > - Make interactive figures that can zoom, pan, and update.
    >  - Customize visual style and layout.
    > - Export to many file formats.
    > - Embed in JupyterLab and Graphical User Interfaces.
   > - Use a rich array of third-party packages built on Matplotlib.

- **Pyjanitor**
  > pyjanitor is a Python implementation of the R package janitor, and provides a clean API for cleaning data.

  > Functionality
  Current functionality includes:
  - Cleaning columns name (multi-indexes are possible!)
  - Removing empty rows and columns
  - Identifying duplicate entries
  - Encoding columns as categorical
  - Splitting your data into features and targets (for machine learning)
  - Adding, removing, and renaming columns
  - Coalesce multiple columns into a single column
  - Date conversions (from matlab, excel, unix) to Python datetime format
  - Expand a single column that has delimited, categorical values into dummy-encoded variables
  - Concatenating and deconcatenating columns, based on a delimiter
  - Syntactic sugar for filtering the dataframe based on queries on a column
  - Experimental submodules for finance, biology, chemistry, engineering, and pyspark

We will use `pyjanitor` primarily to clean and tidy columns throughout this course.


## Getting Started
Now, let us examine each of the above libraries using examples. We will briefly illustrate each package for this course without delving into much detail except for the `pandas` and `matplotlib` libraries, which we will thoroughly explore in the remainder of the course.

### NumPy

You can install the `NumPy` package in several ways. In this course, we will install `NumPy` with either `conda` or `pip` as follows:

In [42]:
# Installing NumPy with conda:
#%conda install numpy

In [41]:
# Installing NumPy with pip:
# %pip install numpy

Note: you may need to restart the kernel to use updated packages.


### Examples
The following examples illustrate how to use `NumPy`.

In [2]:
# Creating a numpy array
import numpy as np
demo = np.array([1, 2, 3, np.nan]) 
demo

array([ 1.,  2.,  3., nan])

In [46]:
# Create an array
arr = np.array([[1, 3, 4, 8], [0, -8, 12, 10]])
arr

array([[ 1,  3,  4,  8],
       [ 0, -8, 12, 10]])

In [4]:
# Example 2 - creating a 3 x 5 matrix
my_matrix = np.array([[4, 2, 0, -6, 7], [8, 10, 4, 15, 12], [0, 2, 8, 13, -9]])

my_matrix

array([[ 4,  2,  0, -6,  7],
       [ 8, 10,  4, 15, 12],
       [ 0,  2,  8, 13, -9]])

In [49]:
# Manipulating NumPy array: pull out the second row
my_matrix[2]

array([ 0,  2,  8, 13, -9])

In [50]:
# Manipulating NumPy array: pull out the first column
my_matrix[:, 3]

array([-6, 15, 13])

In [10]:
# Manipulating NumPy array: pull out the first column
my_matrix[:, 3]

array([-6, 15, 13])

We can also use `NumPy` to create empty arrays or arrays with all zeroes as placeholders. Arrays created with `np.empty` are faster than those created with `np.zeroes`.

In [11]:
# Creating an empty array
np.empty(5)

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [12]:
# Creating an array with ones 
np.ones(3)

array([1., 1., 1.])

In [14]:
# Creating an array with zeroes
np.zeros(4)

array([0., 0., 0., 0.])

In [53]:
# Creating a NumPy array with a range of numbers or elements
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# Creating an array with linearly spaced values in a specified internal
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Adding and sorting elements

In [23]:
my_arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

# Let's sort the elements in our array
my_arr.sort()

# Print the output
my_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
# Adding two arrays together
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Concatenate a with b
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [27]:
# We could also do the following
a = np.array([[1, 2, 0], [3, 4, 4]])
b = np.array([[5, 6, -3]])

np.concatenate((a,b), axis=0)

array([[ 1,  2,  0],
       [ 3,  4,  4],
       [ 5,  6, -3]])

### Checking matrix or array dimension, number of elements, and size

In [28]:
my_matrix_2 = np.array([[[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                        
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]],
                        
                        [[0 ,1 ,2, 3],
                        [4, 5, 6, 7]]
                        ]
                       )
# Print the output
my_matrix_2

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [29]:
# Find the dimensions of this matrix
my_matrix_2.ndim

3

In [30]:
# Compute the number of elements in this matrix
my_matrix_2.size

24

In [31]:
# Find the shape of this matrix
my_matrix_2.shape

(3, 2, 4)

In [60]:
# Reshaping NumPy array
my_arr_2 = np.arange(1, 13)
my_arr_2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
# Reshape my_arr_2 - convert into a 3 x 4 matrix
my_arr_2.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
# Performing mathematical operations on a NumPy array
my_arr_2.sum(axis=0)

78

In [64]:
my_matrix_2.sum(axis=1)

array([[ 4,  6,  8, 10],
       [ 4,  6,  8, 10],
       [ 4,  6,  8, 10]])

In [65]:
my_arr_2.max()

12

In [66]:
my_arr_2.min()

1

### Pandas
In this course, we will be using `pandas 2`, which leverages `PyArrow` in the backend. `PyArrow` is designed to work with tabular and heterogeneous data. Using PyArrow as the pandas backend optimizes and speeds up `pandas`.

### Installing Pandas

Pandas can be installed either with conda or pip, as shown below.

#### Anaconda

In [5]:
# Installing pandas and pyarrow with conda
#%conda install pandas pyarrow seaborn matplotlib 

In [6]:
import pandas as pd
pd.__version__


'2.2.1'

#### Pip

First, we must create a virtual environment containing our project files.

In [ ]:
#python3 -m venv pandas-env
#source pandas-env/bin/activate
# pip install pandas pyarrow

## Data Structures
pandas has two main data structures:

- Series is a one-dimensional array representing a column in a DataFrame.
- DataFrame: a two-dimensional array for representing a tabular, spreadsheet-like data structure (Effective Pandas 2, p.15)

## Data Types

- Data Types
  - Integer
  - Float
  - String
  - Date
  - Categorical
  - Boolean

- Python:
  - int
  - float
  - str
  - datetime
  - bool

- Pandas 2
  - 'inte64[pyarrow]'
  - 'float64[pyarrow]'
  - pd.ArrowDType(pa.String())
  - 'timestamp[ns][pyarrow]' 
  - 'dictionary' 
  - 'bool[pyarrow]'

- Pandas 1
  - 'int64' 
  - 'float64' 
  - object, str
  - 'datetime64[ns]'
  - 'category'
  - bool

### PyArrow and the Future (Effective Pandas 2, p. 22)

>To overcome the annoyances and issues of NumPy in Pandas, for Pandas 2.0, the developers added a new backend, PyArrow. You can think of PyArrow as a next-generation NumPy. It is designed to work with tabular data and heterogeneous data. It also handles missing values in integers and has better support for strings. If you turn on the PyArrow backend, Pandas will be faster and more efficient. However, there might be some rough edges where PyArrow is missing features that NumPy has. I will try and point out these differences in the book.

> PyArrow also allows us to create arrays and tables similar to NumPy. However, we are going to use the library indirectly through Pandas.
For the remainder of the chapter, I want to review the common types and show what they look like in pure Python, Pandas 1.x and Pandas 2.0. I will also show how to convert between the types.

### Importing Datasets

In [14]:
# Import South Sudan 2008 Census Data
import pandas as pd
import numpy as np
import pyarrow as pa
from janitor import clean_names

census_raw = pd.read_csv(
    'Python for Data Science_files/data/ss_2008_census_data_raw.csv', 
    dtype_backend='pyarrow', 
    engine='pyarrow'
    )

In [11]:
census_raw.head(10)

Region Region Name Region - RegionId Variable               Variable Name  \
0  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   
1  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   
2  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   
3  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   
4  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   
5  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   
6  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   
7  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   
8  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   
9  KN.A2  Upper Nile             SS-NU    KN.B2  Population, Total (Number)   

      Age  Age Name  Scale    Units    2008  
0   KN.C1     Total  units  Persons  964353  
1   KN.C2    0 to 4  units  Persons  150872  
2   KN.C3    5 to 9  units  Persons  151467  
3   KN.C4  10 to 14  units  Persons  126140  
4   KN.C5  15 to 19  units  Persons  103804  
5   KN.C6  20 to 24  units  Persons   82588  
6   KN.C7  25 to 29  units  Persons   76754  
7   KN.C8  30 to 34  units  Persons   63134  
8   KN.C9  35 to 39  units  Persons   56806  
9  KN.C10  40 to 44  units  Persons   42139

In [15]:
(census_raw
 .clean_names()
 )

region                                        region_name  \
0            KN.A2                                         Upper Nile   
1            KN.A2                                         Upper Nile   
2            KN.A2                                         Upper Nile   
3            KN.A2                                         Upper Nile   
4            KN.A2                                         Upper Nile   
..             ...                                                ...   
448         KN.A11                                  Eastern Equatoria   
449         KN.A11                                  Eastern Equatoria   
450           <NA>                                               <NA>   
451        Source:         National Bureau of Statistics, South Sudan   
452  Download URL:  http://southsudan.opendataforafrica.org/fvjqdp...   

    region_regionid variable                variable_name     age  age_name  \
0             SS-NU    KN.B2   Population, Total (Number)   KN.C1     Total   
1             SS-NU    KN.B2   Population, Total (Number)   KN.C2    0 to 4   
2             SS-NU    KN.B2   Population, Total (Number)   KN.C3    5 to 9   
3             SS-NU    KN.B2   Population, Total (Number)   KN.C4  10 to 14   
4             SS-NU    KN.B2   Population, Total (Number)   KN.C5  15 to 19   
..              ...      ...                          ...     ...       ...   
448           SS-EE    KN.B8  Population, Female (Number)  KN.C14  60 to 64   
449           SS-EE    KN.B8  Population, Female (Number)  KN.C22       65+   
450            <NA>     <NA>                         <NA>    <NA>      <NA>   
451            <NA>     <NA>                         <NA>    <NA>      <NA>   
452            <NA>     <NA>                         <NA>    <NA>      <NA>   

     scale    units    2008  
0    units  Persons  964353  
1    units  Persons  150872  
2    units  Persons  151467  
3    units  Persons  126140  
4    units  Persons  103804  
..     ...      ...     ...  
448  units  Persons    5274  
449  units  Persons    8637  
450   <NA>     <NA>    <NA>  
451   <NA>     <NA>    <NA>  
452   <NA>     <NA>    <NA>  

[453 rows x 10 columns]

In [16]:
census_df = census_raw.clean_names()

In [ ]:
census_df = census_df[]